### ISSUE TITLE
Template simple nix "check" & validate / formatters workflows in devops-actions

### ISSUE THREAD

**Issue by F-WRunTime** [runtimeverification/devops-actions#3]

**Comment by F-WRunTime** [comment]
https://runtimeverification.slack.com/archives/C03MXPKMP1D/p1657639013927619

action reference would look like in the jobs: 

```yaml
- uses: runtimeverification/devops-actions/cached-nix-build@v1
  with: 
    gc-root: "k"
    build-target: "k"
```
